FROM apache/airflow:2.5.1
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
USER airflow   
RUN pip install apache-airflow-providers-postgres apache-airflow-providers-amazon==7.2.0